services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'kobiton/kobiton-execute-test']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
